#!/bin/csh
#
# CAMx 6.50
#

###setenv NCPUS 3     
###setenv OMP_NUM_THREADS 3
###setenv OMP_STACKSIZE 128M

set EXEC      = "../src/CAMx.v6.50.MPICH.pgf"
#
set RUN     = "v6.50.midwest.36.12.MPICH1"
set INPUT   = "../inputs"
set MET     = "../inputs/met"
set EMIS    = "../emiss"
set PTSRCE  = "../ptsrce"
set OUTPUT  = "../outputs"
#
mkdir -p $OUTPUT
#
#  --- Create the nodes file ---
#
cat << ieof > nodes
10.1.4.2
10.1.4.3
10.1.4.4
10.1.4.5
10.1.4.6
10.1.4.2
10.1.4.3
10.1.4.4
ieof
set NUMPROCS = `wc -l nodes | awk '{print $1+1}'`
#
#  --- set the dates and times ----
#
set RESTART = "NO"
foreach today (03.154 04.155)
set JUL = $today:e
set CAL = $today:r
set YESTERDAY = `echo ${CAL} | awk '{printf("%2.2d",$1-1)}'`
#
if( ${RESTART} == "NO" ) then
        set RESTART = "false"
else
        set RESTART = "true"
endif
#
#  --- Create the input file (always called CAMx.in)
#
cat << ieof > CAMx.in

 &CAMx_Control

 Run_Message      = 'CAMx 6.50 Test Problem -- CF CB6R4 $RUN',

!--- Model clock control ---

 Time_Zone        = 0,                 ! (0=UTC,5=EST,6=CST,7=MST,8=PST)
 Restart          = .${RESTART}.,
 Start_Date_Hour  = 2002,06,${CAL},0000,   ! (YYYY,MM,DD,HHmm)
 End_Date_Hour    = 2002,06,${CAL},2400,   ! (YYYY,MM,DD,HHmm)

 Maximum_Timestep    = 15.,            ! minutes
 Met_Input_Frequency = 60.,            ! minutes
 Ems_Input_Frequency = 60.,            ! minutes
 Output_Frequency    = 60.,            ! minutes

!--- Map projection parameters ---

 Map_Projection = 'LAMBERT',  ! (LAMBERT,POLAR,UTM,LATLON)
 UTM_Zone       = 0,
 Longitude_Pole = -97.,      ! deg (west<0,south<0)
 Latitude_Pole  =  40.,      ! deg (west<0,south<0)
 True_Latitude1 =  45.,      ! deg (west<0,south<0)
 True_Latitude2 =  33.,      ! deg (west<0,south<0)

!--- Parameters for the master (first) grid ---

 Number_of_Grids      = 2,
 Master_SW_XCoord     = -792.,         ! km or deg, SW corner of cell(1,1)
 Master_SW_YCoord     = -1656.,        ! km or deg, SW corner of cell (1,1)
 Master_Cell_XSize    = 36.,           ! km or deg
 Master_Cell_YSize    = 36.,           ! km or deg
 Master_Grid_Columns  = 68,
 Master_Grid_Rows     = 68,
 Number_of_Layers     = 16,

!--- Parameters for the second grid ---

 Nest_Meshing_Factor(2) = 3,           ! Cell size relative to master grid
 Nest_Beg_I_Index(2)    = 22,          ! Relative to master grid
 Nest_End_I_Index(2)    = 51,          ! Relative to master grid
 Nest_Beg_J_Index(2)    = 22,          ! Relative to master grid
 Nest_End_J_Index(2)    = 58,          ! Relative to master grid

!--- Model options ---

 Diagnostic_Error_Check = .false.,      ! True = will stop after 1st timestep
 Advection_Solver       = 'PPM',        ! (PPM,BOTT)
 Chemistry_Solver       = 'EBI',        ! (EBI,IEH,LSODE)
 PiG_Submodel           = 'None',       ! (None,GREASD,IRON)
 Probing_Tool           = 'None',       ! (None,OSAT,GOAT,APCA,PSAT,DDM,PA,RTRAC)
 Chemistry              = .true.,
 Drydep_Model           = 'WESELY89',   ! (None,WESELY89,ZHANG03)
 Wet_Deposition         = .true.,
 ACM2_Diffusion         = .false.,
 Super_Stepping         = .true.,
 Gridded_Emissions      = .true.,
 Point_Emissions        = .true.,
 Ignore_Emission_Dates  = .true.,
 Flexi_Nest             = .false.,
 Inline_Ix_Emissions    = .true.,

!--- Output specifications ---

 Root_Output_Name         = '$OUTPUT/CAMx.$RUN.200206${CAL}',
 Average_Output_3D        = .false.,
 Output_Species_Names(1)   = 'NO',
 Output_Species_Names(2)   = 'NO2',
 Output_Species_Names(3)   = 'O3',
 Output_Species_Names(4)   = 'SO2',
 Output_Species_Names(5)   = 'H2O2',
 Output_Species_Names(6)   = 'HNO3',
 Output_Species_Names(7)   = 'NH3',
 Output_Species_Names(8)   = 'PNO3',
 Output_Species_Names(9)   = 'PSO4',
 Output_Species_Names(10)  = 'PNH4',
 Output_Species_Names(11)  = 'POA',
 Output_Species_Names(12)  = 'PEC',
 Output_Species_Names(13)  = 'FPRM',
 Output_Species_Names(14)  = 'CPRM',
 Output_Species_Names(15)  = 'CCRS',
 Output_Species_Names(16)  = 'FCRS',
 Output_Species_Names(17)  = 'SOA1',
 Output_Species_Names(18)  = 'SOA2',
 Output_Species_Names(19)  = 'SOA3',
 Output_Species_Names(20)  = 'SOA4',

!--- Input files ---

 Chemistry_Parameters = '$INPUT/../inputs/CAMx6.5.chemparam.CB6r4_CF_SOAP_ISORROPIA',
 Photolyis_Rates      = '$INPUT/tuv.do_CB6.020603',
 Ozone_Column         = '$INPUT/o3map.200206.STL_36_68X68_12_92X113.txt',
 Initial_Conditions   = '$INPUT/IC.vistas_2002gt2a_STL_36_68X68_16L.2002081',
 Boundary_Conditions  = '$INPUT/BC.vistas_2002gt2a_STL_36_68X68_16L.2002${JUL}',
 Point_Sources        = '$PTSRCE/ptsrce.stl.36km.2002${JUL}.a0.bin',
 Master_Grid_Restart  = '$OUTPUT/CAMx.$RUN.200206${YESTERDAY}.inst',
 Nested_Grid_Restart  = '$OUTPUT/CAMx.$RUN.200206${YESTERDAY}.finst',
 PiG_Restart          = ' ',

 Surface_Grid(1) = '$INPUT/met/camxv6.2d_sfc.200206${CAL}.36k.bin',
 Met3D_Grid(1)   = '$INPUT/met/camxv6.3d_met.200206${CAL}.36k.bin',
 Met2D_Grid(1)   = '$INPUT/met/camxv6.2d_met.200206${CAL}.36k.bin',
 Vdiff_Grid(1)   = '$INPUT/met/camxv6.3d_kv.200206${CAL}.36k.bin',
 Cloud_Grid(1)   = '$INPUT/met/camxv6.3d_cld.200206${CAL}.36k.bin',
 Emiss_Grid(1)   = '$EMIS/emiss.stl.36km.200206${CAL}.a1.bin',

 Surface_Grid(2) = '$INPUT/met/camxv6.2d_sfc.200206${CAL}.12k.bin',
 Met3D_Grid(2)   = '$INPUT/met/camxv6.3d_met.200206${CAL}.12k.bin',
 Met2D_Grid(2)   = '$INPUT/met/camxv6.2d_met.200206${CAL}.12k.bin',
 Vdiff_Grid(2)   = '$INPUT/met/camxv6.3d_kv.200206${CAL}.12k.bin',
 Cloud_Grid(2)   = '$INPUT/met/camxv6.3d_cld.200206${CAL}.12k.bin',
 Emiss_Grid(2)   = '$EMIS/emiss.stl.12kmsmall.200206${CAL}.a1.bin',

 /
!-------------------------------------------------------------------------------

ieof
#
#  --- Execute the model ---
#
if( ! { mpirun -v -machinefile nodes -np $NUMPROCS $EXEC } ) then
   exit
endif
set RESTART = "YES"

end
